import './capstone/capstone.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import BootstrapClient from './BootstrapClient';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import ChatbotWidget from './components/ChatbotWidget'; 

export const metadata = {
  title: 'Capstone Project',
  description: 'Generated by Group 1',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>      
        <BootstrapClient />
        {children}
        <ChatbotWidget />
      </body>
    </html>
  )
}
